language: python
python:
- "3.6"
before_install:
- export BOTO_CONFIG="/dev/null"
- export AWS_SECRET_ACCESS_KEY="whatever"
- export AWS_ACCESS_KEY_ID="whatever"
- export SECRET_KEY="whatever"
install: "pip install -r requirements.txt"
script:
- ./manage.py test --verbosity=2